// <auto-generated />
using CreatingMembership.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CreatingMembership.Migrations
{
    [DbContext(typeof(MembershipDbContext))]
    [Migration("20211004123249_phase1")]
    partial class phase1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CreatingMembership.Models.Membership", b =>
                {
                    b.Property<string>("username")
                        .HasMaxLength(27)
                        .HasColumnType("character varying(27)");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(27)
                        .HasColumnType("character varying(27)");

                    b.Property<int>("age")
                        .HasMaxLength(1)
                        .HasColumnType("integer");

                    b.HasKey("username");

                    b.ToTable("memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
